import { NextResponse } from "next/server"
import { setFeatures, setOKRs, setSprints, setFeatureOKRMappings, setSprintFeatures, setActivityLogs } from "@/lib/db"
import type { Feature, OKR, Sprint, FeatureOKRMapping, SprintFeature, ActivityLog } from "@/lib/db-types"

export async function POST() {
  try {
    // Seed OKRs
    const okrsData: OKR[] = [
      {
        id: 1,
        title: "Increase User Engagement",
        description: "Drive 30% increase in daily active users",
        type: "objective",
        parent_id: null,
        target_value: 30,
        current_value: 12,
        progress: 40,
        quarter: "Q1",
        year: 2025,
        owner: "Product Team",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        title: "Improve Platform Performance",
        description: "Reduce API latency and improve scalability",
        type: "objective",
        parent_id: null,
        target_value: 40,
        current_value: 25,
        progress: 63,
        quarter: "Q1",
        year: 2025,
        owner: "Engineering Team",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        title: "Expand Market Reach",
        description: "Enter 3 new geographic markets",
        type: "objective",
        parent_id: null,
        target_value: 3,
        current_value: 1,
        progress: 33,
        quarter: "Q2",
        year: 2025,
        owner: "Growth Team",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        title: "Increase DAU by 30%",
        description: "Daily Active Users growth",
        type: "key-result",
        parent_id: 1,
        target_value: 100000,
        current_value: 45000,
        progress: 45,
        quarter: "Q1",
        year: 2025,
        owner: "Product Team",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        title: "Reduce churn rate to 5%",
        description: "Customer retention improvement",
        type: "key-result",
        parent_id: 1,
        target_value: 5,
        current_value: 7,
        progress: 0,
        quarter: "Q1",
        year: 2025,
        owner: "Product Team",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]
    setOKRs(okrsData)

    // Seed Features
    const featuresData: Feature[] = [
      {
        id: 1,
        title: "Real-time Collaboration",
        description: "Enable multiple users to edit roadmaps simultaneously with live updates",
        status: "in-progress",
        reach: 5000,
        impact: 3,
        confidence: 80,
        effort: 8,
        rice_score: 150,
        priority: 1,
        category: "Core Features",
        tags: ["collaboration", "real-time"],
        target_quarter: "Q1 2025",
        owner: "Sarah Chen",
        team: "Engineering",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        title: "Advanced RICE Calculator",
        description: "Interactive RICE scoring with what-if analysis and historical trends",
        status: "planned",
        reach: 3000,
        impact: 2,
        confidence: 90,
        effort: 5,
        rice_score: 108,
        priority: 2,
        category: "Analytics",
        tags: ["prioritization", "analytics"],
        target_quarter: "Q1 2025",
        owner: "Mike Johnson",
        team: "Product",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        title: "Mobile Dashboard",
        description: "Native mobile app for roadmap viewing and quick updates",
        status: "backlog",
        reach: 8000,
        impact: 2,
        confidence: 60,
        effort: 13,
        rice_score: 73.8,
        priority: 5,
        category: "Mobile",
        tags: ["mobile", "dashboard"],
        target_quarter: "Q2 2025",
        owner: "Lisa Park",
        team: "Mobile Team",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        title: "Jira Integration",
        description: "Two-way sync with Jira for seamless workflow integration",
        status: "planned",
        reach: 4000,
        impact: 3,
        confidence: 85,
        effort: 8,
        rice_score: 127.5,
        priority: 3,
        category: "Integrations",
        tags: ["integration", "jira"],
        target_quarter: "Q1 2025",
        owner: "David Kumar",
        team: "Engineering",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        title: "AI-Powered Prioritization",
        description: "ML-based feature prioritization suggestions",
        status: "backlog",
        reach: 6000,
        impact: 3,
        confidence: 50,
        effort: 21,
        rice_score: 42.9,
        priority: 7,
        category: "AI/ML",
        tags: ["ai", "automation"],
        target_quarter: "Q3 2025",
        owner: "Emma Wilson",
        team: "Data Science",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        title: "Custom Reporting",
        description: "Build custom reports and export to PDF/Excel",
        status: "in-progress",
        reach: 2500,
        impact: 2,
        confidence: 95,
        effort: 5,
        rice_score: 95,
        priority: 4,
        category: "Analytics",
        tags: ["reporting", "export"],
        target_quarter: "Q1 2025",
        owner: "Tom Anderson",
        team: "Product",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        title: "Stakeholder Portal",
        description: "Read-only portal for executives and stakeholders",
        status: "planned",
        reach: 1000,
        impact: 2,
        confidence: 80,
        effort: 3,
        rice_score: 53.3,
        priority: 6,
        category: "Access Control",
        tags: ["portal", "stakeholders"],
        target_quarter: "Q2 2025",
        owner: "Rachel Green",
        team: "Engineering",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        title: "Roadmap Templates",
        description: "Pre-built templates for common roadmap patterns",
        status: "completed",
        reach: 7000,
        impact: 1,
        confidence: 100,
        effort: 2,
        rice_score: 350,
        priority: 0,
        category: "Templates",
        tags: ["templates", "onboarding"],
        target_quarter: "Q4 2024",
        owner: "Chris Lee",
        team: "Product",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]
    setFeatures(featuresData)

    // Seed Sprints
    const sprintsData: Sprint[] = [
      {
        id: 1,
        name: "Sprint 23",
        goal: "Complete real-time collaboration MVP",
        start_date: new Date("2025-01-06"),
        end_date: new Date("2025-01-19"),
        status: "active",
        velocity: 42,
        team: "Engineering",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        name: "Sprint 24",
        goal: "Launch RICE calculator and custom reporting",
        start_date: new Date("2025-01-20"),
        end_date: new Date("2025-02-02"),
        status: "planned",
        velocity: 38,
        team: "Product",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        name: "Sprint 22",
        goal: "Foundation work for integrations",
        start_date: new Date("2024-12-23"),
        end_date: new Date("2025-01-05"),
        status: "completed",
        velocity: 45,
        team: "Engineering",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]
    setSprints(sprintsData)

    // Seed mappings
    const mappingsData: FeatureOKRMapping[] = [
      { id: 1, feature_id: 1, okr_id: 1, alignment_score: 95, created_at: new Date() },
      { id: 2, feature_id: 1, okr_id: 4, alignment_score: 85, created_at: new Date() },
      { id: 3, feature_id: 2, okr_id: 1, alignment_score: 80, created_at: new Date() },
      { id: 4, feature_id: 4, okr_id: 2, alignment_score: 90, created_at: new Date() },
      { id: 5, feature_id: 6, okr_id: 1, alignment_score: 75, created_at: new Date() },
      { id: 6, feature_id: 7, okr_id: 1, alignment_score: 70, created_at: new Date() },
      { id: 7, feature_id: 3, okr_id: 3, alignment_score: 85, created_at: new Date() },
    ]
    setFeatureOKRMappings(mappingsData)

    const sprintFeaturesData: SprintFeature[] = [
      { id: 1, sprint_id: 1, feature_id: 1, story_points: 13, created_at: new Date() },
      { id: 2, sprint_id: 1, feature_id: 6, story_points: 8, created_at: new Date() },
      { id: 3, sprint_id: 2, feature_id: 2, story_points: 8, created_at: new Date() },
      { id: 4, sprint_id: 2, feature_id: 4, story_points: 13, created_at: new Date() },
      { id: 5, sprint_id: 3, feature_id: 8, story_points: 5, created_at: new Date() },
    ]
    setSprintFeatures(sprintFeaturesData)

    const activityLogsData: ActivityLog[] = [
      {
        id: 1,
        entity_type: "feature",
        entity_id: 1,
        action: "status_changed",
        user_name: "Sarah Chen",
        details: { from: "planned", to: "in-progress" },
        created_at: new Date(),
      },
      {
        id: 2,
        entity_type: "feature",
        entity_id: 1,
        action: "rice_updated",
        user_name: "Mike Johnson",
        details: { reach: 5000, impact: 3, confidence: 80, effort: 8 },
        created_at: new Date(),
      },
    ]
    setActivityLogs(activityLogsData)

    return NextResponse.json({
      success: true,
      message: "Database seeded successfully",
      counts: {
        features: featuresData.length,
        okrs: okrsData.length,
        sprints: sprintsData.length,
      },
    })
  } catch (error) {
    return NextResponse.json({ error: "Failed to seed database" }, { status: 500 })
  }
}
