import type { Feature, OKR, Sprint } from "./types"

export const mockOKRs: OKR[] = [
  {
    id: "okr-1",
    title: "Increase User Engagement",
    description: "Drive higher user engagement across the platform",
    type: "objective",
    parentId: null,
    targetValue: 100,
    currentValue: 65,
    progress: 65,
    quarter: "Q1 2025",
    owner: "Product Team",
  },
  {
    id: "okr-2",
    title: "Improve Daily Active Users by 40%",
    description: "Increase DAU from 10k to 14k",
    type: "key-result",
    parentId: "okr-1",
    targetValue: 14000,
    currentValue: 11200,
    progress: 55,
    quarter: "Q1 2025",
    owner: "Growth Team",
  },
  {
    id: "okr-3",
    title: "Reduce Time to Value",
    description: "Help users achieve value faster",
    type: "objective",
    parentId: null,
    targetValue: 100,
    currentValue: 45,
    progress: 45,
    quarter: "Q1 2025",
    owner: "Product Team",
  },
  {
    id: "okr-4",
    title: "Decrease Onboarding Time by 50%",
    description: "Reduce average onboarding from 10 min to 5 min",
    type: "key-result",
    parentId: "okr-3",
    targetValue: 5,
    currentValue: 7,
    progress: 60,
    quarter: "Q1 2025",
    owner: "UX Team",
  },
  {
    id: "okr-5",
    title: "Expand Market Reach",
    description: "Enter new market segments",
    type: "objective",
    parentId: null,
    targetValue: 100,
    currentValue: 30,
    progress: 30,
    quarter: "Q1 2025",
    owner: "Business Team",
  },
]

export const mockSprints: Sprint[] = [
  {
    id: "sprint-1",
    name: "Sprint 24 - Q1 Kickoff",
    startDate: "2025-01-06",
    endDate: "2025-01-19",
    status: "completed",
    capacity: 80,
    velocity: 75,
  },
  {
    id: "sprint-2",
    name: "Sprint 25 - Engagement Focus",
    startDate: "2025-01-20",
    endDate: "2025-02-02",
    status: "active",
    capacity: 80,
    velocity: 0,
  },
  {
    id: "sprint-3",
    name: "Sprint 26 - UX Improvements",
    startDate: "2025-02-03",
    endDate: "2025-02-16",
    status: "planning",
    capacity: 80,
    velocity: 0,
  },
]

export const mockFeatures: Feature[] = [
  {
    id: "feat-1",
    title: "Real-time Collaboration",
    description:
      "Enable multiple users to collaborate on documents simultaneously with live cursors and presence indicators",
    status: "in-progress",
    priority: "critical",
    reach: 8,
    impact: 9,
    confidence: 7,
    effort: 8,
    riceScore: 63,
    okrIds: ["okr-1", "okr-2"],
    sprintId: "sprint-2",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-20T14:30:00Z",
    tags: ["collaboration", "real-time", "core-feature"],
  },
  {
    id: "feat-2",
    title: "Advanced Search & Filters",
    description: "Implement full-text search with advanced filtering capabilities across all content types",
    status: "planned",
    priority: "high",
    reach: 9,
    impact: 7,
    confidence: 8,
    effort: 5,
    riceScore: 100.8,
    okrIds: ["okr-1", "okr-2"],
    sprintId: "sprint-3",
    createdAt: "2025-01-10T09:00:00Z",
    updatedAt: "2025-01-18T11:00:00Z",
    tags: ["search", "ux", "productivity"],
  },
  {
    id: "feat-3",
    title: "Interactive Onboarding Tutorial",
    description: "Create an interactive step-by-step tutorial to guide new users through key features",
    status: "in-progress",
    priority: "high",
    reach: 10,
    impact: 8,
    confidence: 9,
    effort: 4,
    riceScore: 180,
    okrIds: ["okr-3", "okr-4"],
    sprintId: "sprint-2",
    createdAt: "2025-01-12T08:00:00Z",
    updatedAt: "2025-01-22T16:00:00Z",
    tags: ["onboarding", "ux", "retention"],
  },
  {
    id: "feat-4",
    title: "Mobile App - iOS",
    description: "Native iOS application with core functionality and offline support",
    status: "backlog",
    priority: "medium",
    reach: 7,
    impact: 9,
    confidence: 6,
    effort: 10,
    riceScore: 37.8,
    okrIds: ["okr-5"],
    sprintId: null,
    createdAt: "2025-01-05T12:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
    tags: ["mobile", "ios", "expansion"],
  },
  {
    id: "feat-5",
    title: "Analytics Dashboard",
    description: "Comprehensive analytics dashboard with customizable widgets and export capabilities",
    status: "planned",
    priority: "medium",
    reach: 6,
    impact: 7,
    confidence: 8,
    effort: 6,
    riceScore: 56,
    okrIds: ["okr-1"],
    sprintId: "sprint-3",
    createdAt: "2025-01-08T14:00:00Z",
    updatedAt: "2025-01-19T09:00:00Z",
    tags: ["analytics", "reporting", "insights"],
  },
  {
    id: "feat-6",
    title: "API Rate Limiting",
    description: "Implement intelligent rate limiting to prevent abuse while maintaining good UX",
    status: "completed",
    priority: "high",
    reach: 5,
    impact: 8,
    confidence: 9,
    effort: 3,
    riceScore: 120,
    okrIds: [],
    sprintId: "sprint-1",
    createdAt: "2024-12-20T10:00:00Z",
    updatedAt: "2025-01-18T15:00:00Z",
    tags: ["infrastructure", "security", "performance"],
  },
  {
    id: "feat-7",
    title: "Dark Mode Support",
    description: "Full dark mode theme with automatic switching based on system preferences",
    status: "completed",
    priority: "low",
    reach: 8,
    impact: 5,
    confidence: 10,
    effort: 2,
    riceScore: 200,
    okrIds: ["okr-1"],
    sprintId: "sprint-1",
    createdAt: "2024-12-15T11:00:00Z",
    updatedAt: "2025-01-10T13:00:00Z",
    tags: ["ui", "accessibility", "ux"],
  },
  {
    id: "feat-8",
    title: "Webhook Integration System",
    description: "Allow users to configure webhooks for real-time event notifications",
    status: "backlog",
    priority: "low",
    reach: 4,
    impact: 6,
    confidence: 7,
    effort: 5,
    riceScore: 33.6,
    okrIds: [],
    sprintId: null,
    createdAt: "2025-01-03T09:00:00Z",
    updatedAt: "2025-01-12T10:00:00Z",
    tags: ["integration", "api", "automation"],
  },
]
